package entity;
// Generated 02-feb-2021 23:54:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Partida generated by hbm2java
 */

@Entity
@Table(name = "partida", schema = "damas")
public class Partida  implements java.io.Serializable {


     private Integer idP;
     private String ganador;
     private Date fechaYhora;
     private Set moviments = new HashSet(0);

    public Partida() {
    }

    public Partida(String ganador) {
        this.ganador = ganador;
    }
    
    public Partida(String ganador, Set moviments) {
       this.ganador = ganador;
       this.moviments = moviments;
    }
    
    @Id
    @GeneratedValue
    @Column(name = "idP")
    public int getIdP() {
        return this.idP;
    }
    
    public void setIdP(Integer idP) {
        this.idP = idP;
    }
    
    @Column(name = "ganador")
    public String getGanador() {
        return this.ganador;
    }
    
    public void setGanador(String ganador) {
        this.ganador = ganador;
    }
    
    @Column(name = "fechaYhora")
    public Date getFechaYhora() {
        return this.fechaYhora;
    }
    
    public void setFechaYhora(Date fechaYhora) {
        this.fechaYhora = fechaYhora;
    }

    public Set getMoviments() {
        return this.moviments;
    }
    
    public void setMoviments(Set moviments) {
        this.moviments = moviments;
    }


}


