package entity;
// Generated 31-ene-2021 19:37:40 by Hibernate Tools 4.3.1



/**
 * Partida generated by hbm2java
 */
public class Partida  implements java.io.Serializable {


     private int idPartida;
     private int ganador;

    public Partida() {
    }

    public Partida(int idPartida, int ganador) {
       this.idPartida = idPartida;
       this.ganador = ganador;
    }
   
    public int getIdPartida() {
        return this.idPartida;
    }
    
    public void setIdPartida(int idPartida) {
        this.idPartida = idPartida;
    }
    public int getGanador() {
        return this.ganador;
    }
    
    public void setGanador(int ganador) {
        this.ganador = ganador;
    }




}


