/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package damas_marianavarro;

import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class Damas_NuevaPartida extends javax.swing.JFrame {
    
    /**
     * Creates new form Damas_NuevaPartida
     */
    
    boolean jugaX = true;
    boolean jugaO = false;
    int filaOrigen = -1;
    int columnaOrigen = -1;
    int filaDestino = -1;
    int columnaDestino = -1;

    public Damas_NuevaPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taula = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        taula.setBackground(new java.awt.Color(158, 139, 81));
        taula.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        taula.setForeground(new java.awt.Color(255, 255, 255));
        taula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"   X", null, "   X", null, "   X", null, "   X", null},
                {null, "   X", null, "   X", null, "   X", null, "   X"},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {"   O", null, "   O", "", "   O", null, "   O", null},
                {null, "   O", null, "   O", null, "   O", null, "   O"}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        taula.setFocusable(false);
        taula.setGridColor(new java.awt.Color(99, 82, 31));
        taula.setRowHeight(50);
        taula.setSelectionBackground(new java.awt.Color(99, 82, 31));
        taula.setSelectionForeground(new java.awt.Color(99, 82, 31));
        taula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taulaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taula);

        jButton1.setText("Sortir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taulaMouseClicked
        // TODO add your handling code here:
        int fila = obtenirFilaClicada();
        int columna = obtenirColumnaClicada();
        
        if(noHiHaOrigen()) {
            if(jugaX && EsX(fila, columna)){
                ActualitzaNouOrigen(fila,columna);
            } else if(jugaO && EsO(fila, columna)){
                ActualitzaNouOrigen(fila,columna);
            } else {
                mostraError();
            }
        } else {
            if(movimentValid(fila, columna)){
                if(esBuit(fila, columna)||OcupatContrari(fila, columna)){
                    mou(fila,columna);
                } else if(OcupatPropi(fila,columna)){
                    actualitzaNouOrigen(fila,columna);
                }
            } else {
                mostraErrorMoviment();
            }
        }
    }//GEN-LAST:event_taulaMouseClicked
    
    private int obtenirFilaClicada() {
        return taula.getSelectedRow();
    }

    private int obtenirColumnaClicada() {
        return taula.getSelectedColumn();
    }
    
    public boolean noHiHaOrigen(){
        boolean nOrigen = false;
        if(filaOrigen == -1 || columnaOrigen == -1){
            nOrigen = true;
        }
        return nOrigen;
    }
    
    private boolean EsX(int fila, int columna) {
        boolean x = false;
        if(taula.getValueAt(fila, columna) == "X") {
            x = true;
        }
        return x;
    }

    private boolean EsO(int fila, int columna) {
        boolean o = false;
        if(taula.getValueAt(fila, columna) == "O") {
            o = true;
        }
        return o;
    }
    
    public void ActualitzaNouOrigen(int fila, int columna){
        filaOrigen = fila;
        columnaOrigen = columna;
    }
    
    public void mostraError(){
        JOptionPane.showMessageDialog(null, "Error!!", "Juego damas", 
                JOptionPane.ERROR_MESSAGE);
        filaOrigen = -1;
        columnaOrigen = -1;
    }
    
    public boolean movimentValid(int fila, int columna) {
        boolean esMovimentValid = false;
        filaDestino = fila;
        columnaDestino = columna;
        int calculaFila =  filaDestino - filaOrigen;
        int calculaColumna = columnaDestino - columnaOrigen;
        
        if(jugaO && (calculaFila == -1) && 
                ((calculaColumna == 1) || (calculaColumna ==  -1))){
            esMovimentValid = true;
        } else if (jugaX && (calculaFila == 1) && 
                ((calculaColumna == 1) || (calculaColumna ==  -1))) {
            esMovimentValid = true;
        }
        return esMovimentValid;
    }
    
    public boolean esBuit(int fila, int columna) {
        boolean buit = false;
        if(taula.getValueAt(fila, columna) == null){
            buit = true;
        }
        return buit;
    }

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Damas_NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Damas_NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Damas_NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Damas_NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Damas_NuevaPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable taula;
    // End of variables declaration//GEN-END:variables


}
