/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package damas_marianavarro;

import static damas_marianavarro.Damas_cargarPartida.results;
import static damas_marianavarro.Damas_cargarPartida.sesion;
import entity.Movimiento;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author maria
 */
public class Damas_RecuperarCualquiera extends javax.swing.JFrame {

    static Session sesion;
    static List results;
    static Movimiento moviment;
    int contador = 0;
    
    /**
     * Creates new form Damas_RecuperarCualquiera
     * @throws java.sql.SQLException
     */
    public Damas_RecuperarCualquiera() throws SQLException {
        initComponents();
        sesion = NewHibernateUtil.getSessionFactory().openSession();
        TablaIds();
       mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        taula = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        ButtonContinuar = new javax.swing.JButton();
        ButtonSelecciona = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        taula1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        taulaLlista = new javax.swing.JTable();
        ButtonSalir1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();

        taula.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"X", null, "X", null, "X", null, "X", null},
                {null, "X", null, "X", null, "X", null, "X"},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {"O", null, "O", null, "O", null, "O", null},
                {null, "O", null, "O", null, "O", null, "O"}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ));
        taula.setRowHeight(50);
        taula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taulaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(taula);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonContinuar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        ButtonContinuar.setText("Continuar");
        ButtonContinuar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 111, 34));

        ButtonSelecciona.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        ButtonSelecciona.setText("Selecciona");
        ButtonSelecciona.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButtonSelecciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSeleccionaActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSelecciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 100, 34));

        taula1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        taula1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"X", null, "X", null, "X", null, "X", null},
                {null, "X", null, "X", null, "X", null, "X"},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {"O", null, "O", null, "O", null, "O", null},
                {null, "O", null, "O", null, "O", null, "O"}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ));
        taula1.setRowHeight(50);
        taula1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taula1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(taula1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 561, -1));

        taulaLlista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(taulaLlista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 320));

        ButtonSalir1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        ButtonSalir1.setText("Salir");
        ButtonSalir1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ButtonSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalir1ActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, 83, 34));

        jLabel1.setText("Has seleccionado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));
        jPanel1.add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_taulaMouseClicked

    private void ButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonContinuarActionPerformed
        // TODO add your handling code here:
        
        //Compruebo si ya ha llegado al ultimo movimiento
        if (contador < results.size()) {
            moviment = (Movimiento) results.get(contador);
            //Sale por pantalla el movimiento que le toca segun lo que ha guardado la base de datos
            taula1.setValueAt(taula1.getValueAt(moviment.getColumnaOrigen(), moviment.getFilaOrigen()), moviment.getColumnaValida(), moviment.getFilaValida());
            taula1.setValueAt(null, moviment.getColumnaOrigen(), moviment.getFilaOrigen());
            contador++;
        } else {
            Damas_P1 damas = new Damas_P1();
            damas.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_ButtonContinuarActionPerformed

    private void ButtonSeleccionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSeleccionaActionPerformed
        // TODO add your handling code here:
        int fila = taulaLlista.getSelectedRow();
        if(fila >= 0){
            valor.setText(taulaLlista.getValueAt(fila, 0).toString());
        } else {
            JOptionPane.showMessageDialog(null, "No has seleccionat cap fila");
        }
        contador=0;
        taula1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"X", null, "X", null, "X", null, "X", null},
                {null, "X", null, "X", null, "X", null, "X"},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {"O", null, "O", null, "O", null, "O", null},
                {null, "O", null, "O", null, "O", null, "O"}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }));
        TablaCargada();
    }//GEN-LAST:event_ButtonSeleccionaActionPerformed

    private void taula1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taula1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_taula1MouseClicked

    private void ButtonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalir1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ButtonSalir1ActionPerformed

    
    private void TablaIds() {
        try{
            sesion.beginTransaction();
            Query query;
            query = sesion.createQuery("SELECT idPartida FROM Partida");
            results = query.list();
            sesion.getTransaction().commit();
        } catch (HibernateException he){
            he.printStackTrace();
        }
    }
    
    public void mostrarTabla() throws SQLException {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id Partida");
        
        taulaLlista.setModel(model); 
        String[] datos  = new String[2];
        String sql = "SELECT idPartida FROM Partida";
        try {
            for(int i = 0; i < results.size(); i++) {
                datos[0] = results.get(i).toString();
                model.addRow(datos);
            }
            taulaLlista.setModel(model);
        } catch (Exception e) {
        
        }       
    }
    
    private void TablaCargada() {
        try{
            sesion.beginTransaction();
            Query query;
            query = sesion.createQuery("FROM Movimiento WHERE partida.idPartida = " + Integer.parseInt(valor.getText()) );
            results = query.list();
            sesion.getTransaction().commit();
        } catch (HibernateException he){
            he.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Damas_RecuperarCualquiera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Damas_RecuperarCualquiera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Damas_RecuperarCualquiera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Damas_RecuperarCualquiera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Damas_RecuperarCualquiera().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Damas_RecuperarCualquiera.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonContinuar;
    private javax.swing.JButton ButtonSalir1;
    private javax.swing.JButton ButtonSelecciona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable taula;
    private javax.swing.JTable taula1;
    private javax.swing.JTable taulaLlista;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
