/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenuf2m6_marianavarro;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class Reset extends javax.swing.JFrame {
    ExamenUf2M6_MariaNavarro connect  = new ExamenUf2M6_MariaNavarro();
    Connection conection;
    /**
     * Creates new form Reset
     */
    public Reset() throws SQLException, ClassNotFoundException {
        initComponents();
        this.conection = connect.conexioJDBC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUsuari = new javax.swing.JLabel();
        jLabelContra = new javax.swing.JLabel();
        Usuari = new javax.swing.JTextField();
        Contrasenya = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        pregunta = new javax.swing.JLabel();
        Respuesta = new javax.swing.JTextField();
        nom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelUsuari.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelUsuari.setText("Usuari: ");

        jLabelContra.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelContra.setText("Introdueix la nova contrasenya: ");

        reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        pregunta.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        nom.setText("COMPROVA NOM");
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pregunta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelUsuari)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelContra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Usuari, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(Contrasenya, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(Respuesta))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(nom)
                .addGap(70, 70, 70)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuari)
                    .addComponent(Usuari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Respuesta)
                    .addComponent(pregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContra))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(nom))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        if(!Usuari.getText().equals("") && !Respuesta.getText().equals("") && !Contrasenya.getText().equals("")) {
            try {
                Statement comando=conection.createStatement();
                ResultSet comparar = comando.executeQuery("SELECT usuari FROM usuaris WHERE usuari = '" + Usuari.getText() + "'");

                if(comparar.next()){
                    pregunta.setText(comando.executeQuery("SELECT pregunta FROM usuaris WHERE usuari = '" + Usuari.getText() + "'").toString());
                    comando.executeQuery("SELECT resposta FROM usuaris WHERE resposta = '" + Respuesta.getText() + "'");
                    comando.executeUpdate("INSERT INTO usuaris VALUES ('" + Usuari.getText() + "','" + Contrasenya.getText() + "','" + Respuesta.getText() + "')");
                    JOptionPane.showMessageDialog(null, "Contrasenya cambiada"); 
                    Menu menu = new Menu();
                    menu.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "ERROR: Reset incorrecte");
                    Menu menu = new Menu();
                    menu.setVisible(true);
                    dispose();   
                }
                                
            } catch (Exception e) {
                 Logger.getLogger(CrearUsuari.class.getName()).log(Level.SEVERE, null, e);
            }
        } else {
           JOptionPane.showMessageDialog(null, "Falten camps per omplir");
        }     
    }//GEN-LAST:event_resetActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
        if(!Usuari.getText().equals("") ) {
            try {
                Statement comando=conection.createStatement();
                ResultSet comparar = comando.executeQuery("SELECT usuari FROM usuaris WHERE usuari = '" + Usuari.getText() + "'");

                if(comparar.next()){
                    pregunta.setText(comando.executeQuery("SELECT pregunta FROM usuaris WHERE usuari = '" + Usuari.getText() + "'").toString());
                    
                } else {
                    JOptionPane.showMessageDialog(null, "ERROR: Reset incorrecte");
                    
                }
                                
            } catch (Exception e) {
                 Logger.getLogger(CrearUsuari.class.getName()).log(Level.SEVERE, null, e);
            }
        } else {
           JOptionPane.showMessageDialog(null, "Falten camps per omplir");
        }     
    }//GEN-LAST:event_nomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Reset().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Reset.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Reset.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contrasenya;
    private javax.swing.JTextField Respuesta;
    private javax.swing.JTextField Usuari;
    private javax.swing.JLabel jLabelContra;
    private javax.swing.JLabel jLabelUsuari;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nom;
    private javax.swing.JLabel pregunta;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
