/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen_m3_marianavarro;

/**
 *
 * @author maria
 */
public class Examen_Maria extends javax.swing.JFrame {

    private int resultat = 0;
    private int dia1 = 0;

    /**
     * Creates new form NewJFrame
     */
    public Examen_Maria() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        TFDies = new javax.swing.JTextField();
        RBXina = new javax.swing.JRadioButton();
        RBItalia = new javax.swing.JRadioButton();
        RBResta = new javax.swing.JRadioButton();
        jBCalcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Dies passats:");

        TFDies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFDiesActionPerformed(evt);
            }
        });

        RBXina.setText("Xina");
        RBXina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBXinaActionPerformed(evt);
            }
        });

        RBItalia.setText("Itàlia");
        RBItalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBItaliaActionPerformed(evt);
            }
        });

        RBResta.setText("Resta");
        RBResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBRestaActionPerformed(evt);
            }
        });

        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Infectats:");

        jLTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLTotal.setForeground(new java.awt.Color(204, 0, 0));
        jLTotal.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFDies, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(RBXina)
                        .addGap(18, 18, 18)
                        .addComponent(RBItalia)
                        .addGap(18, 18, 18)
                        .addComponent(RBResta)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFDies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBXina)
                    .addComponent(RBItalia)
                    .addComponent(RBResta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jBCalcular)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLTotal))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFDiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFDiesActionPerformed

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        // TODO add your handling code here:
        calcul(resultat);
        jLTotal.setText(String.valueOf(resultat));
    }//GEN-LAST:event_jBCalcularActionPerformed

    private void RBXinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBXinaActionPerformed
        // TODO add your handling code here:
//        resultat = 0;
        int temporal = resultat;
        resultat = Integer.parseInt(TFDies.getText());
        if (resultat > 0) {
            resultat = resultat + (3 * resultat);
            temporal = temporal + resultat;
        } else {
            resultat = 1;
        }
    }//GEN-LAST:event_RBXinaActionPerformed

    private void RBItaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBItaliaActionPerformed
        // TODO add your handling code here:
        int temporal = resultat;
        resultat = Integer.parseInt(TFDies.getText());
        if (resultat > 0) {
            resultat = (2 * resultat);
            temporal = temporal + resultat;
            resultat = temporal;
        } else {
            resultat = 1;
        }
    }//GEN-LAST:event_RBItaliaActionPerformed

    private void RBRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBRestaActionPerformed
        // TODO add your handling code here:
        int temporal = resultat;
        resultat = 0;
        resultat = Integer.parseInt(TFDies.getText());
        if (resultat > 0) {
            resultat = resultat + resultat;
        }
    }//GEN-LAST:event_RBRestaActionPerformed

    private int calcul(int resultat) {
        if (RBXina.isSelected()) {
            return resultat;
        } else if (RBItalia.isSelected()) {
            return resultat;
        } else if (RBResta.isSelected()) {
            return resultat;
        }
        return resultat;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen_Maria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen_Maria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen_Maria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen_Maria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen_Maria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBItalia;
    private javax.swing.JRadioButton RBResta;
    private javax.swing.JRadioButton RBXina;
    private javax.swing.JTextField TFDies;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCalcular;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
